module Kettle
  module Gha
    module Pins
      VERSION: String
      module Version
        VERSION: String
      end
      # See the writing guide of rbs: https://github.com/ruby/rbs#guides
    end
  end
end
